In [1]:
number = 15

In [2]:
type(number)

int

In [3]:
dir(number)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 'real',
 'to_bytes

In [4]:
my_list = [1, 2, 3]

In [5]:
dir(my_list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

### Numpy

In [6]:
import numpy as np

In [7]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [8]:
array_a = np.array([1, 2, 3, 4])

In [9]:
array_b = np.array([0, .5, 1, 1.5, 2])

In [10]:
array_b

array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
array_a[0]

1

In [12]:
array_b[-1]

2.0

In [13]:
array_a[:2]

array([1, 2])

In [14]:
array_a.dtype

dtype('int32')

In [15]:
array_b.dtype

dtype('float64')

In [16]:
empty_array = np.array([])

In [17]:
empty_array.dtype

dtype('float64')

In [18]:
np.array([1, 2, 3, 4], dtype = np.float_)

array([1., 2., 3., 4.])

In [19]:
np.array([1, 2, 3, 4], dtype = np.int8)

array([1, 2, 3, 4], dtype=int8)

In [20]:
array_c = np.array(["ada", "lovelace"])

In [21]:
array_c.dtype

dtype('<U8')

### Dimensions and Shapes

In [22]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [23]:
array_a.shape

(4,)

In [24]:
my_array.shape

(2, 3)

In [25]:
array_a.ndim

1

In [26]:
my_array.ndim

2

In [27]:
my_array.size

6

In [28]:
my_array = np.array([
    [
        [12, 11, 10],
        [9, 8, 7]
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [29]:
my_array.ndim

3

In [30]:
my_array.shape

(2, 2, 3)

In [31]:
my_array.size

12

### Indexing and Slicing

In [32]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [33]:
my_array[1]

array([4, 5, 6])

In [34]:
my_array[1][0]

4

In [35]:
my_array[1, 0]

4

In [36]:
my_array[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
my_array[:2, :2]

array([[1, 2],
       [4, 5]])

In [38]:
my_array[1] = np.array([10, 10, 10])

In [39]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [40]:
my_array[2] = 99

In [41]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [43]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [45]:
my_array = np.arange(0, 10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
my_array.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [49]:
np.arange(1, 10.1, 4)

array([1., 5., 9.])

In [50]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [51]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [53]:
np.ones((2, 5, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [55]:
np.eye(5, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
my_array = np.random.random((5, 2))

In [57]:
my_array

array([[0.58001215, 0.71933254],
       [0.28275198, 0.5191459 ],
       [0.12133525, 0.85303941],
       [0.41638476, 0.85646033],
       [0.18863708, 0.47085889]])

In [58]:
np.random.randint(100, size = (5, 5))

array([[44, 29, 66, 59, 73],
       [47, 13, 23,  3, 32],
       [58, 59, 53, 18, 96],
       [40,  3, 69, 75, 85],
       [38, 86,  3, 28, 77]])

In [59]:
np.random.randint(100, size = (5, 5, 2))

array([[[48,  3],
        [77, 87],
        [10, 73],
        [34, 43],
        [40, 76]],

       [[26, 41],
        [34, 72],
        [80, 48],
        [55, 25],
        [78,  2]],

       [[ 1, 97],
        [95, 17],
        [89,  5],
        [63, 24],
        [95, 98]],

       [[45, 77],
        [ 9, 61],
        [64, 68],
        [68, 32],
        [56, 16]],

       [[69, 81],
        [ 7, 52],
        [73, 13],
        [78, 37],
        [33, 76]]])

In [61]:
np.linspace(5, 10, 5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [62]:
# any(), all(), full(), concatenate()

In [63]:
array1 = np.arange(0, 10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
array1 = array1.reshape(2, 5)

In [65]:
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [66]:
np.concatenate([array1, array1])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [67]:
np.concatenate([array1, array1], axis = 0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [68]:
np.concatenate([array1, array1], axis = 1)

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

### Statics

In [72]:
array1 = np.arange(0, 10)
array1 = array1.reshape(2, 5)

In [73]:
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [74]:
array1.sum()

45

In [75]:
array1.mean()

4.5

In [76]:
array1.std()

2.8722813232690143

In [77]:
array1.var()

8.25

In [79]:
array1.sum(axis = 1)

array([10, 35])

In [80]:
array1.sum(axis = 0)

array([ 5,  7,  9, 11, 13])

In [81]:
array1 + 10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [82]:
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [83]:
array1 += 10
array1

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [86]:
array2 = np.arange(0, 10)
array2 = array2.reshape(5, 2)
array2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [85]:
array2 + 10
array2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [87]:
array2 = array2 + 10
array2

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

### Boolean Arrays

In [88]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [90]:
a[0], a[-1]

(0, 3)

In [91]:
a[[0, -1]]

array([0, 3])

In [92]:
a[[True, False, False, True]]

array([0, 3])

In [93]:
a >= 2

array([False, False,  True,  True])

In [94]:
a[a >= 2]

array([2, 3])

In [95]:
a.mean()

1.5

In [96]:
a[a > a.mean()]

array([2, 3])

In [97]:
a[~(a > a.mean())]

array([0, 1])

In [98]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [99]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [100]:
# 100'e kadar rastgele tamsayılardan oluşan 3,3 bir matris oluşturun.
# 30'dan büyük olanları boolean yöntemi ile filtreleyin.

In [101]:
matris = np.random.randint(100, size = (3, 3))

In [102]:
matris

array([[29, 80, 29],
       [67, 21, 21],
       [36, 41, 91]])

In [112]:
boolean_array = matris > 30

In [114]:
boolean_array

array([[False,  True, False],
       [ True, False, False],
       [ True,  True,  True]])

In [115]:
matris[boolean_array]

array([80, 67, 36, 41, 91])

In [116]:
my_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array_1 = my_array.reshape(5, 2)
array_2 = my_array.reshape(2, 5)

In [117]:
array_1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [118]:
array_2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [119]:
np.dot(array_1, array_2)

array([[  5,   6,   7,   8,   9],
       [ 15,  20,  25,  30,  35],
       [ 25,  34,  43,  52,  61],
       [ 35,  48,  61,  74,  87],
       [ 45,  62,  79,  96, 113]])

In [120]:
array_2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [121]:
import sys

In [122]:
sys.getsizeof(10)

28

In [124]:
sys.getsizeof(1000**100)

160

In [127]:
np.dtype(int).itemsize

4

In [128]:
np.dtype(np.int8).itemsize

1

In [129]:
np.dtype(float).itemsize

8

In [130]:
sys.getsizeof([1, 2, 3])

88

In [131]:
np.array([1, 2, 3]).nbytes

12

In [132]:
my_list = list(range(100000))

In [133]:
my_array = np.arange(100000)

In [134]:
%time np.sum(my_array ** 2)

CPU times: total: 0 ns
Wall time: 1.01 ms


216474736

In [135]:
%time np.sum([number ** 2 for number in my_list])

CPU times: total: 31.2 ms
Wall time: 27.4 ms


333328333350000